export type ScriptChannel = "sms" | "email" | "phone" | "dm";
export type ScriptScenario = "generic" | "bank" | "delivery" | "tech_support" | "government" | "job" | "marketplace" | "romance";
export type ScriptTone = "polite" | "firm" | "nuclear";

export type ReplyScript = {
  id: string;
  channel: ScriptChannel;
  scenario: ScriptScenario;
  tone: ScriptTone;
  label: string;
  text: string;
  whyItWorks: string;
  isFree: boolean;
};

export const REPLY_SCRIPTS: ReplyScript[] = [
  // ── FREE SCRIPTS (5) ──
  {
    id: "free-sms-generic",
    channel: "sms",
    scenario: "generic",
    tone: "polite",
    label: "General SMS reply",
    text: "Thanks for reaching out, but I don't respond to unexpected messages. If this is legitimate, I'll contact the company directly through their official website.",
    whyItWorks: "Politely shuts down the conversation without providing any information. Doesn't confirm your identity or that the number is active.",
    isFree: true,
  },
  {
    id: "free-email-generic",
    channel: "email",
    scenario: "generic",
    tone: "polite",
    label: "General email reply",
    text: "Thank you for your message. I do not click links or provide personal information via email. If this is regarding a legitimate matter, I will contact your organization directly through official channels.",
    whyItWorks: "Professional tone that doesn't reveal whether you have an account. Redirects to official channels, which scammers can't control.",
    isFree: true,
  },
  {
    id: "free-phone-generic",
    channel: "phone",
    scenario: "generic",
    tone: "polite",
    label: "General phone script",
    text: "I appreciate you calling, but I don't handle account matters or payments over inbound calls. I'll look up the official number and call back directly. Thank you.",
    whyItWorks: "Ends the call without being rude. 'I'll call back directly' removes the scammer's control of the conversation.",
    isFree: true,
  },
  {
    id: "free-dm-generic",
    channel: "dm",
    scenario: "generic",
    tone: "polite",
    label: "General DM reply",
    text: "Hey, I don't share personal info or click links in DMs. If this is about something real, let's talk through an official channel.",
    whyItWorks: "Casual but firm. Sets a clear boundary without escalating. If they're legitimate, they'll understand.",
    isFree: true,
  },
  {
    id: "free-sms-delivery",
    channel: "sms",
    scenario: "delivery",
    tone: "polite",
    label: "Delivery fee text",
    text: "I'll track my package directly through the carrier's official website. I don't pay fees through text messages. Thanks.",
    whyItWorks: "Addresses the specific delivery scam without clicking any links. Shows you know how real tracking works.",
    isFree: true,
  },

  // ── PREMIUM SMS SCRIPTS ──
  {
    id: "sms-bank-polite",
    channel: "sms",
    scenario: "bank",
    tone: "polite",
    label: "Bank alert (polite)",
    text: "Thanks for the alert. I'll call my bank directly using the number on my card to verify. Please don't send any more messages.",
    whyItWorks: "Acknowledges without confirming you have an account. The phrase 'number on my card' signals you know how real banks work.",
    isFree: false,
  },
  {
    id: "sms-bank-firm",
    channel: "sms",
    scenario: "bank",
    tone: "firm",
    label: "Bank alert (firm)",
    text: "My bank doesn't contact me this way. I'm verifying directly. Do not contact this number again.",
    whyItWorks: "Short and authoritative. Demonstrates awareness that banks don't request action via SMS.",
    isFree: false,
  },
  {
    id: "sms-bank-nuclear",
    channel: "sms",
    scenario: "bank",
    tone: "nuclear",
    label: "Bank alert (block)",
    text: "This is a scam. Reported and blocked.",
    whyItWorks: "Maximum efficiency. No information given, conversation ended. Sometimes less is more.",
    isFree: false,
  },
  {
    id: "sms-delivery-firm",
    channel: "sms",
    scenario: "delivery",
    tone: "firm",
    label: "Delivery fee (firm)",
    text: "Delivery companies don't charge fees via text. I've reported this number to my carrier.",
    whyItWorks: "States a fact that undermines the scam premise. Mentioning reporting adds deterrence.",
    isFree: false,
  },
  {
    id: "sms-delivery-nuclear",
    channel: "sms",
    scenario: "delivery",
    tone: "nuclear",
    label: "Delivery fee (block)",
    text: "Scam. Reported to 7726.",
    whyItWorks: "Minimal engagement. 7726 (SPAM) is the real carrier reporting number, which shows you're informed.",
    isFree: false,
  },
  {
    id: "sms-tech-polite",
    channel: "sms",
    scenario: "tech_support",
    tone: "polite",
    label: "Tech support (polite)",
    text: "I don't handle tech support through text messages. If there's a real issue, I'll contact the company's official support directly.",
    whyItWorks: "Politely disengages while making it clear you know this isn't how real tech support works.",
    isFree: false,
  },
  {
    id: "sms-govt-polite",
    channel: "sms",
    scenario: "government",
    tone: "polite",
    label: "Government text (polite)",
    text: "Government agencies don't request payments or personal information via text. I'll contact the agency directly if needed.",
    whyItWorks: "States a well-known fact that dismantles the scam. No information revealed.",
    isFree: false,
  },
  {
    id: "sms-govt-firm",
    channel: "sms",
    scenario: "government",
    tone: "firm",
    label: "Government text (firm)",
    text: "The IRS/SSA does not text people. This is being reported. Do not contact me again.",
    whyItWorks: "Names the agencies scammers impersonate and states the policy they violate. Very direct.",
    isFree: false,
  },

  // ── PREMIUM EMAIL SCRIPTS ──
  {
    id: "email-bank-polite",
    channel: "email",
    scenario: "bank",
    tone: "polite",
    label: "Bank email (polite)",
    text: "Thank you for this notification. For security reasons, I verify all account matters by calling the number on my debit card or visiting my local branch. I will not click links in emails.",
    whyItWorks: "Professional and calm. Demonstrates knowledge of proper security practices without revealing account details.",
    isFree: false,
  },
  {
    id: "email-bank-firm",
    channel: "email",
    scenario: "bank",
    tone: "firm",
    label: "Bank email (firm)",
    text: "I do not verify account information through email links. If this is legitimate, it will show in my official banking app. This email has been reported to my bank's fraud department.",
    whyItWorks: "Firm boundary. Mentioning the fraud department signals you're informed and taking action.",
    isFree: false,
  },
  {
    id: "email-invoice-polite",
    channel: "email",
    scenario: "marketplace",
    tone: "polite",
    label: "Fake invoice (polite)",
    text: "I don't recognize this invoice. I'll verify through my account on the company's official website. Please do not send follow-ups.",
    whyItWorks: "Doesn't confirm or deny the purchase. Redirects verification to the real channel.",
    isFree: false,
  },
  {
    id: "email-invoice-firm",
    channel: "email",
    scenario: "marketplace",
    tone: "firm",
    label: "Fake invoice (firm)",
    text: "This invoice does not match any of my records. I'm verifying directly with the vendor. If this is fraudulent, it has been forwarded to their abuse team.",
    whyItWorks: "Professional pushback. 'Forwarded to abuse team' creates accountability pressure.",
    isFree: false,
  },
  {
    id: "email-job-polite",
    channel: "email",
    scenario: "job",
    tone: "polite",
    label: "Job offer (polite)",
    text: "Thank you for reaching out. Before proceeding, I'd like to verify this opportunity through your company's official careers page. Could you share the job posting URL on your company website?",
    whyItWorks: "Appears interested while requesting verification that scammers can't provide. Legitimate recruiters will happily share.",
    isFree: false,
  },
  {
    id: "email-job-firm",
    channel: "email",
    scenario: "job",
    tone: "firm",
    label: "Job offer (firm)",
    text: "I don't provide personal information or pay fees for job opportunities. Legitimate employers don't require this. If this role is real, please direct me to the official job listing.",
    whyItWorks: "Names two specific scam tactics (info harvesting and upfront fees). Sets a clear standard for legitimacy.",
    isFree: false,
  },
  {
    id: "email-tech-polite",
    channel: "email",
    scenario: "tech_support",
    tone: "polite",
    label: "Tech support email (polite)",
    text: "I appreciate the notification. I'll check my account status directly through the official website/app. I don't click links or download attachments from unexpected emails.",
    whyItWorks: "Polite refusal that covers both phishing vectors — links and attachments.",
    isFree: false,
  },
  {
    id: "email-generic-firm",
    channel: "email",
    scenario: "generic",
    tone: "firm",
    label: "General email (firm)",
    text: "I do not respond to unsolicited emails requesting action, information, or payment. If this is legitimate, contact me through verified official channels.",
    whyItWorks: "Covers all three common scam goals in one sentence. Very efficient.",
    isFree: false,
  },
  {
    id: "email-generic-nuclear",
    channel: "email",
    scenario: "generic",
    tone: "nuclear",
    label: "General email (block)",
    text: "This email has been reported as phishing. No further correspondence will be read from this address.",
    whyItWorks: "Final. No room for social engineering follow-ups. Mentioning the report adds weight.",
    isFree: false,
  },

  // ── PREMIUM PHONE SCRIPTS ──
  {
    id: "phone-bank-polite",
    channel: "phone",
    scenario: "bank",
    tone: "polite",
    label: "Bank call (polite)",
    text: "Thank you for calling. For my security, I'm going to hang up and call my bank directly using the number on my card. If this is legitimate, you'll understand.",
    whyItWorks: "The magic phrase 'number on my card' removes the scammer's ability to redirect you. Polite but immovable.",
    isFree: false,
  },
  {
    id: "phone-bank-firm",
    channel: "phone",
    scenario: "bank",
    tone: "firm",
    label: "Bank call (firm)",
    text: "I don't verify account information on inbound calls. I'm hanging up now and calling my bank directly.",
    whyItWorks: "Short and non-negotiable. Establishes that you have a security policy and you follow it.",
    isFree: false,
  },
  {
    id: "phone-tech-polite",
    channel: "phone",
    scenario: "tech_support",
    tone: "polite",
    label: "Tech support call (polite)",
    text: "I appreciate the concern, but I don't give remote access or install software based on phone calls. If there's a real issue, I'll take my device to a certified service center.",
    whyItWorks: "Addresses the two main tech support scam tactics — remote access and software installs — while offering a legitimate alternative.",
    isFree: false,
  },
  {
    id: "phone-tech-firm",
    channel: "phone",
    scenario: "tech_support",
    tone: "firm",
    label: "Tech support call (firm)",
    text: "Microsoft, Apple, and Google do not make unsolicited support calls. I'm ending this call and reporting the number.",
    whyItWorks: "Names the companies scammers impersonate most. Demonstrates awareness that cuts through the pretense.",
    isFree: false,
  },
  {
    id: "phone-govt-polite",
    channel: "phone",
    scenario: "government",
    tone: "polite",
    label: "Government call (polite)",
    text: "Thank you. Government agencies typically communicate through official mail first. I'm going to verify this by calling the agency's published phone number. Have a good day.",
    whyItWorks: "States how real government agencies actually operate. 'Published phone number' removes scammer control.",
    isFree: false,
  },
  {
    id: "phone-govt-firm",
    channel: "phone",
    scenario: "government",
    tone: "firm",
    label: "Government call (firm)",
    text: "The IRS does not call to demand immediate payment or threaten arrest. I'm hanging up and reporting this number to the FTC.",
    whyItWorks: "Names the most common government impersonation and its red flags. Very direct.",
    isFree: false,
  },
  {
    id: "phone-generic-nuclear",
    channel: "phone",
    scenario: "generic",
    tone: "nuclear",
    label: "Any call (immediate hang-up)",
    text: "I don't handle anything over unsolicited calls. Goodbye.",
    whyItWorks: "Sometimes the safest response is the shortest. Zero engagement means zero risk.",
    isFree: false,
  },
  {
    id: "phone-romance-polite",
    channel: "phone",
    scenario: "romance",
    tone: "polite",
    label: "Online romance call (polite)",
    text: "I've enjoyed talking with you, but I'm not comfortable sending money or sharing financial information with someone I haven't met in person. I hope you understand.",
    whyItWorks: "Warm but firm. Sets the boundary at in-person meeting, which romance scammers can never fulfill.",
    isFree: false,
  },

  // ── PREMIUM DM SCRIPTS ──
  {
    id: "dm-marketplace-polite",
    channel: "dm",
    scenario: "marketplace",
    tone: "polite",
    label: "Marketplace deal (polite)",
    text: "Thanks for the offer, but I only do transactions through the platform's official checkout. I don't send money directly through DMs or external payment apps.",
    whyItWorks: "Redirects to the platform's buyer protection. Scammers need to go off-platform to avoid protections.",
    isFree: false,
  },
  {
    id: "dm-marketplace-firm",
    channel: "dm",
    scenario: "marketplace",
    tone: "firm",
    label: "Marketplace deal (firm)",
    text: "I don't transact outside the platform. If you can't do this through official checkout with buyer protection, I'm not interested.",
    whyItWorks: "Makes buyer protection the non-negotiable requirement. Legitimate sellers will comply.",
    isFree: false,
  },
  {
    id: "dm-romance-polite",
    channel: "dm",
    scenario: "romance",
    tone: "polite",
    label: "Romance DM (polite)",
    text: "I appreciate the connection, but I have a personal rule about not sending money or sharing financial details with people I've only met online. I hope you understand.",
    whyItWorks: "Frames it as a 'personal rule' rather than suspicion, which is harder to argue against.",
    isFree: false,
  },
  {
    id: "dm-romance-firm",
    channel: "dm",
    scenario: "romance",
    tone: "firm",
    label: "Romance DM (firm)",
    text: "I don't send money to people I haven't met in person. If you're in a real emergency, please contact local services. I won't be sending anything.",
    whyItWorks: "Directly addresses the common 'emergency' angle. Offers a legitimate alternative while holding the boundary.",
    isFree: false,
  },
  {
    id: "dm-crypto-polite",
    channel: "dm",
    scenario: "marketplace",
    tone: "polite",
    label: "Crypto/investment DM (polite)",
    text: "Thanks, but I don't invest based on DM recommendations. If this is a real opportunity, I'll research it independently through verified financial sources.",
    whyItWorks: "Shows you know that legitimate investments don't recruit through DMs. Redirects to independent research.",
    isFree: false,
  },
  {
    id: "dm-crypto-firm",
    channel: "dm",
    scenario: "marketplace",
    tone: "firm",
    label: "Crypto/investment DM (firm)",
    text: "Unsolicited investment advice in DMs is a scam. I'm reporting this account. Don't message me again.",
    whyItWorks: "Calls it what it is. Short, final, and includes the report threat.",
    isFree: false,
  },
  {
    id: "dm-generic-firm",
    channel: "dm",
    scenario: "generic",
    tone: "firm",
    label: "General DM (firm)",
    text: "I don't click links, share personal info, or send money through DMs. If you have a legitimate reason to contact me, use an official channel.",
    whyItWorks: "Covers all three DM scam vectors in one sentence. Clear, firm, done.",
    isFree: false,
  },
  {
    id: "dm-generic-nuclear",
    channel: "dm",
    scenario: "generic",
    tone: "nuclear",
    label: "General DM (block)",
    text: "Reported and blocked.",
    whyItWorks: "Two words. Maximum disengagement. No information given.",
    isFree: false,
  },
  {
    id: "dm-job-polite",
    channel: "dm",
    scenario: "job",
    tone: "polite",
    label: "Job opportunity DM (polite)",
    text: "Thanks for reaching out. I'd love to learn more — could you send me the official job posting on your company's careers page? I prefer to apply through official channels.",
    whyItWorks: "Appears receptive while requesting something scammers can't provide — a verifiable listing.",
    isFree: false,
  },
  {
    id: "dm-job-firm",
    channel: "dm",
    scenario: "job",
    tone: "firm",
    label: "Job opportunity DM (firm)",
    text: "Real recruiters don't ask for fees or personal information through DMs. If this is a real role, direct me to the company's official application portal.",
    whyItWorks: "Names the scam tactics upfront. Sets a standard that only legitimate opportunities can meet.",
    isFree: false,
  },
];

export const FREE_SCRIPT_COUNT = REPLY_SCRIPTS.filter((s) => s.isFree).length;
export const TOTAL_SCRIPT_COUNT = REPLY_SCRIPTS.length;

export const SCENARIO_LABELS: Record<ScriptScenario, string> = {
  generic: "General",
  bank: "Banking",
  delivery: "Delivery",
  tech_support: "Tech support",
  government: "Government",
  job: "Job offers",
  marketplace: "Shopping & crypto",
  romance: "Romance",
};

export const TONE_LABELS: Record<ScriptTone, string> = {
  polite: "Polite",
  firm: "Firm",
  nuclear: "Block & report",
};
